name: Update Submodules
on: workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Khởi tạo và cập nhật submodule
        run: |
          git submodule update --init --recursive

      - name: Kiểm tra thay đổi .gitmodules (tùy chọn)
        run: |
          git status --short .gitmodules  # Kiểm tra xem file .gitmodules có thay đổi không
          if [[ $(git status --porcelain | grep -Ec '.gitmodules') -gt 0 ]]; then
            git commit -m "Cập nhật .gitmodules"  # Cam kết thay đổi cho .gitmodules
            git push origin HEAD:main  # Đẩy thay đổi lên origin (tùy chọn)
          fi

      - name: Thêm Tweaks/YouPiP (nếu cần)
        run: |
          if [ ! -d Tweaks/YouPiP ]; then  # Kiểm tra xem thư mục đã tồn tại
            git submodule add Tweaks/YouPiP https://github.com/PoomSmart/YouPiP.git
          fi

      - name: Cập nhật Tweaks/YouPiP (nếu có)
        run: |
          if [ -d Tweaks/YouPiP ]; then  # Kiểm tra xem thư mục đã tồn tại
            git submodule update --remote Tweaks/YouPiP
          fi

      - name: Kiểm tra mã thoát
        run: |
          exit_code=$?
          if [ $exit_code -ne 0 ]; then
            echo "Cập nhật submodule thất bại với mã thoát $exit_code"
            exit 1
          fi
